### ISSUE TITLE
Opzioni sviluppatore

### ISSUE THREAD

**Issue by 0rlaf** [MishFdM/MIUI_V10_Italy#115]
Nuovo apk

<img src="https://preview.ibb.co/c2X2Gz/IMG_20181004_020144.jpg" alt="IMG_20181004_020144">

**Comment by ale8530** [comment]
inserito stringhe inglesi, verificare da smartphone le stringhe che vengono visualizzate e tradurre solo quelle

**Comment by ale8530** [comment]
https://github.com/MishFdM/MIUI_V10_Italy/commit/a688afd9211963ded1a7c0bec1f4a2858f54674f
