### ISSUE TITLE
Alcuni screenshot di parti non tradotti

### ISSUE THREAD

**Issue by mymo1982** [MishFdM/MIUI_V10_Italy#137]
Salve, posto alcuni screenshot presi dalla 8.19.25

<a href="https://ibb.co/bN6toA"><img src="https://preview.ibb.co/jqdjvq/IMG-20181026-205640.jpg" alt="IMG-20181026-205640" border="0"></a>

<a href="https://ibb.co/dVpJMV"><img src="https://preview.ibb.co/e8P7Fq/Screenshot-2018-10-26-20-58-22-909-com-android-settings.jpg" alt="Screenshot-2018-10-26-20-58-22-909-com-android-settings" border="0"></a>

<a href="https://ibb.co/mvOg8A"><img src="https://preview.ibb.co/mBpcgV/Screenshot-2018-10-26-23-54-54-237-com-miui-home.jpg" alt="Screenshot-2018-10-26-23-54-54-237-com-miui-home" border="0"></a>

**Comment by 0rlaf** [comment]
@ale8530 Due di questi bug sono presenti solo sulla rom .eu.

Posso confermare in quanto l'override del layout temi (terzo screen) è stato implementato solo lì.

**Comment by mymo1982** [comment]
Sì, sono bug della 8.10.25 (prima avevo scritto 8.19) .EU
Chiedo solo per chiarezza, i bug della EU vanno o non vanno segnalati qui?

**Comment by 0rlaf** [comment]
La EU sfrutta le nostre traduzioni. Quindi si, si possono segnalare qui.

Tuttavia pa loro correzione non è assicurata. Vedremo con ale se sarà possibile.

**Comment by ale8530** [comment]
Dispositivo?

**Comment by mymo1982** [comment]
Redmi note 4x (Mido)
