### ISSUE TITLE
Notifiche sovrapposte

### ISSUE THREAD

**Issue by Truciolo** [MishFdM/MIUI_V10_Italy#147]
Buonasera,
saltuariamente riscontro un bug alle notifiche, che vengono visualizzate sovrapposte le une alle altre, nel menu a tendina.

1) Miui dev eu 10.2 v. 8.11.8 (anche precedente 8.11.1)
2) Xiaomi Mi Mix2
3) Screenshot qui
https://preview.ibb.co/iVY7nq/IMG-20181112-210725.jpg

**Comment by ale8530** [comment]
non è un bug miui.it
