### ISSUE TITLE
Menu avanzato di riavvio

### ISSUE THREAD

**Issue by dmaglio** [MishFdM/MIUI_V10_Italy#208]
MIUI 10.3 - 9.2.14

![screenshot_2019-02-15-16-02-07-444_com miui home](https://user-images.githubusercontent.com/446573/52865258-8921c000-313c-11e9-9c23-352585d2aa81.png)

**Comment by ale8530** [comment]
Stringhe non esistenti nella nostra repo, non è un bug di traduzione, fare capo allo sviluppatore della rom.

**Comment by ale8530** [comment]
@ingbrzy this screenshot no bug italian translate, you can fix on your rom?

Thanks

**Comment by dmaglio** [comment]
@ale8530 sul sito della xiaomi.eu mi riporta questo link per segnalare i bug di traduzione...

**Comment by ale8530** [comment]
Sto parlando con lo sviluppatore non ci sono stringhe da noi credo che sia un problema loro
