### ISSUE TITLE
Traduzione sezione Suoni e vibrazione 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V10_Italy#22]
![screenshot_2018-07-08-04-00-42-960_com android settings](https://user-images.githubusercontent.com/22075569/42416018-c7406ad6-8263-11e8-87b2-8b3b7cb6c654.png)

Oltre all'italiano errato in Silenzioso, manca proprio l'italiano in Non disturbare

**Comment by 0rlaf** [comment]
https://github.com/MishFdM/MIUI_V10_Italy/pull/23

**Comment by ale8530** [comment]
Thanks Orlaf
