### ISSUE TITLE
Traduzioni Cit.apk

### ISSUE THREAD

**Issue by Oizaro** [MishFdM/MIUI_V10_Italy#229]
<img src="https://i.ibb.co/yg3fbKR/IMG-20190225-234046.jpg">
<img src="https://i.ibb.co/ZSV3WJW/IMG-20190225-234022.jpg">
<img src="https://i.ibb.co/vDVyy2H/IMG-20190225-233953.jpg">
<img src="https://i.ibb.co/mcZygPM/Screenshot-2019-02-25-23-39-39-174-com-miui-cit.png">

**Comment by ale8530** [comment]
Chiusa non è da fixare al momento
