### ISSUE TITLE
Correzioni traduzioni

### ISSUE THREAD

**Issue by Oizaro** [MishFdM/MIUI_V10_Italy#234]
<STRONG>Security Center</STRONG>

<STRONG>Correggere in: Liberati</STRONG>

<img src="https://i.ibb.co/b7fGXhW/Screenshot-2019-03-02-03-25-51-292-com-miui-securitycenter.jpg">

**Comment by Oizaro** [comment]
<STRONG>Correggere: "voto" in "volto" e "ocn" in "con"</STRONG>

<img src="https://i.ibb.co/fNtgynW/IMG-20190301-010543.jpg">

**Comment by Oizaro** [comment]
<STRONG>Correggere in: Annulla</STRONG>

<img src="https://i.ibb.co/sVt6drR/IMG-20190301-013552.jpg">

**Comment by ale8530** [comment]
Su respingi ho preferito mettere "Fatto" perchè la traduzione corretta è quella se va modificata analizziamo dopo
