### ISSUE TITLE
issue  translations italian

### ISSUE THREAD

**Issue by Antonpet97** [MishFdM/MIUI_V10_Italy#268]
![IMG_20190718_152420](https://user-images.githubusercontent.com/22517681/61461836-da471180-a971-11e9-8ff8-187baf1466e5.jpg)
![IMG_20190718_152517](https://user-images.githubusercontent.com/22517681/61461837-da471180-a971-11e9-954b-41b57728d617.jpg)
![IMG_20190718_152637](https://user-images.githubusercontent.com/22517681/61461838-da471180-a971-11e9-8c90-86d1c0693ce7.jpg)
![IMG_20190718_152807](https://user-images.githubusercontent.com/22517681/61461841-db783e80-a971-11e9-8325-697bea268116.jpg)
![IMG_20190718_153040](https://user-images.githubusercontent.com/22517681/61461842-db783e80-a971-11e9-8162-f5fdb56af161.jpg)
![IMG_20190718_153120](https://user-images.githubusercontent.com/22517681/61461843-db783e80-a971-11e9-8456-0d3e42ab078c.jpg)
 
in the latest version of EU 9.7.11 there are some strings not translated into Italian I hope this problem is solved.

**Comment by ale8530** [comment]
Come vedi le stringhe non sono aggiornate da un mese in italiano.

Aggiorneremo in questi giorni. 

Issue chiusa

**Comment by ale8530** [comment]
Leggere qui-->https://github.com/MishFdM/MIUI_V10_Italy/issues/270
