### ISSUE TITLE
Traduzioni mancanti

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V10_Italy#270]
Buonasera, ho l'ultima Xiaomi EU (9.7.25) e noto tante traduzioni mancanti. Ne riporto alcune (non sono tutte però:

In Impostazioni: Lock screen, Notifications, Home screen, Passwords e Security, Screen Times.

In Impostazioni -> Lock screen -> La descrizione di doppio tocco per risvegliare è in inglese; poi Tap fingerprint sensor to wake insieme alla descrizione; Power menu access e Quick setting access insieme alla descrizione di entrambe; la descrizione di Fotocamera Rapida.

In Impostazioni -> Schermo -> Status bar e anche alcune opzioni all'interno di Status bar sono in inglese: Show Lte icon for 4g e Quick settings layout.

Anche la sezione "Need other settings?" è in inglese. 

Queste sono solo alcune delle traduzioni mancanti

Grazie

**Comment by Federic095** [comment]
Mi sono dimenticato di scrivere il dispositivo: Redmi Note 5 (HMNote5PRO)

**Comment by ale8530** [comment]
Chiusa per le stesse motivazioni di questa issue https://github.com/MishFdM/MIUI_V10_Italy/issues/268

**Comment by ale8530** [comment]
Abbiamo effettuato un grosso aggiornamento di traduzione i bug dovrebbero essere risolti.
