### ISSUE TITLE
problema microfono e capsula auricolare

### ISSUE THREAD

**Issue by gio125** [MishFdM/MIUI_V10_Italy#271]
Ciao,
su Redmi K20 Pro China 6gb 128 gb, ROM 3.16.0 Xaiomi.eu, riscontro non funzionamento del microfono e della capsula auricolare dopo qualche ora dall'accensione. Il malfunzionamento non riguarda solo le chiamate ma anche le app che utilizzano di microfono e capsula auricolare. Il problema si risolve con riavvio del terminale.
 Con ROM stock China era tutto ok.

Grazie
Giordano

**Comment by ale8530** [comment]
Qui bug traduzione miui.it o xiaomi.eu per i bug devi scrivere sul forum xiaomi.eu
