### ISSUE TITLE
Can we improve our Italian translations about Miui 11

### ISSUE THREAD

**Issue by xzj8b3** [MishFdM/MIUI_V10_Italy#272]
I have a Redmi Note 7 and I think this Rom is really great.

If we could improve the translations also in Italian would be the TOP, I think it's a shame a Roma made really so well has small shortcomings!!!!

Too beautiful really congratulations for the great work!!!!

**Comment by ale8530** [comment]
This is repo Italian translation miui 10...miui.it stop supporting translation miui 11

**Comment by xzj8b3** [comment]
> This is repo Italian translation miui 10...miui.it stop supporting translation miui 11

In fact, I wanted to put him on 11 and I was wrong!!!!!
