### ISSUE TITLE
Things to translate in italian (MIUi 11 Mi 9 pro 5g)

### ISSUE THREAD

**Issue by Haerikan** [MishFdM/MIUI_V10_Italy#273]
![Screenshot_2019-11-16-16-37-33-152_com miui home](https://user-images.githubusercontent.com/57838539/68995575-a46a5900-088f-11ea-9954-642b416a36c8.jpg)
![IMG_20191116_163605](https://user-images.githubusercontent.com/57838539/68995576-a46a5900-088f-11ea-880c-7c7ff143c145.jpg)
![IMG_20191116_163714](https://user-images.githubusercontent.com/57838539/68995577-a46a5900-088f-11ea-8089-f4fbfbef8a0a.jpg)
![Screenshot_2019-11-16-16-37-29-781_com miui home](https://user-images.githubusercontent.com/57838539/68995578-a502ef80-088f-11ea-9bc4-0a39e82c2011.jpg)
![IMG_20191116_163546](https://user-images.githubusercontent.com/57838539/68995579-a502ef80-088f-11ea-956e-5cf3f896ccc1.jpg)
![Screenshot_2019-11-16-16-39-03-146_com miui securitycenter](https://user-images.githubusercontent.com/57838539/68995580-a502ef80-088f-11ea-95b6-c9a20f6dc356.jpg)
![Screenshot_2019-11-16-16-36-26-962_com miui securitycenter](https://user-images.githubusercontent.com/57838539/68995581-a502ef80-088f-11ea-8191-50ac6266b789.jpg)
![Screenshot_2019-11-16-16-39-05-117_com miui securitycenter](https://user-images.githubusercontent.com/57838539/68995582-a59b8600-088f-11ea-87b8-7d1553dcbbc1.jpg)
![IMG_20191116_163753](https://user-images.githubusercontent.com/57838539/68995583-a59b8600-088f-11ea-80ca-5bdc4243b82d.jpg)
![Screenshot_2019-11-16-16-38-18-985_com miui notes](https://user-images.githubusercontent.com/57838539/68995584-a59b8600-088f-11ea-947e-a51e20dc374a.jpg)
![IMG_20191116_163618](https://user-images.githubusercontent.com/57838539/68995585-a59b8600-088f-11ea-85e3-f51488bcb9f3.jpg)
![IMG_20191116_163530](https://user-images.githubusercontent.com/57838539/68995586-a6341c80-088f-11ea-9ae4-1e70fa1f1e8e.jpg)
![IMG_20191116_163646](https://user-images.githubusercontent.com/57838539/68995588-a6341c80-088f-11ea-995a-c8b897e91336.jpg)
![Screenshot_2019-11-16-16-36-54-707_com miui securitycenter](https://user-images.githubusercontent.com/57838539/68995589-a6341c80-088f-11ea-9ab7-b42621deac73.jpg)

**Comment by Haerikan** [comment]
![Screenshot_2019-11-16-16-40-50-097_com android settings](https://user-images.githubusercontent.com/57838539/68995611-e1365000-088f-11ea-9afb-9a33c5abcb13.jpg)

**Comment by Haerikan** [comment]
![Screenshot_2019-11-16-16-40-27-767_com android settings](https://user-images.githubusercontent.com/57838539/68995619-f57a4d00-088f-11ea-9032-bfdab0ad52b3.jpg)
![Screenshot_2019-11-16-16-40-22-557_com android settings](https://user-images.githubusercontent.com/57838539/68995620-f57a4d00-088f-11ea-8418-e745163c06f7.jpg)
![Screenshot_2019-11-16-16-40-50-097_com android settings](https://user-images.githubusercontent.com/57838539/68995621-f7dca700-088f-11ea-92e0-bba38dbc3ff8.jpg)

**Comment by ale8530** [comment]
This is miui 10 repo...Closed
