### ISSUE TITLE
Traduzioni

### ISSUE THREAD

**Issue by soloxme** [MishFdM/MIUI_V10_Italy#31]
![thumbnail_screenshot_2018-07-09-11-22-07-847_lockscreen](https://user-images.githubusercontent.com/40915841/42442540-3ae61b0e-836b-11e8-9a3b-c83c367d744b.png)

Xiaomi MI6, MIUI 8.7.5 Xiaomi.eu

**Comment by ale8530** [comment]
Devono sistemare le stringhe loro, la traduzione è corretta.

Chiusa

**Comment by ale8530** [comment]
Ho chiesto a ingbrzy di sistemare la stringa direttamente nella sua rom, senza causare conflitto con la nostra ROM.
