### ISSUE TITLE
Correzione traduzione

### ISSUE THREAD

**Issue by N7eXodus** [MishFdM/MIUI_V10_Italy#51]
https://github.com/MishFdM/MIUI_V10_Italy/blob/93010f41a4106c4b37e46bb4d12e22734d7f1881/Italian/main/Calendar.apk/res/values-it/strings.xml#L320

Sarebbe più corretto scrivere "Orario promemoria per Eventi Giornalieri" dato che fa riferimento all'orario degli eventi impostati come "Tutto il Giorno"

**Comment by 0rlaf** [comment]
https://github.com/MishFdM/MIUI_V10_Italy/pull/52
