### ISSUE TITLE
Step Counter issue

### ISSUE THREAD

**Issue by cordamarcel** [MishFdM/MIUI_V10_Italy#61]
In Italian language stepcounter show "0 passo" ever. In english language it work pretty good. Please make something.

**Comment by 0rlaf** [comment]
Bug della tua release...

Però una curiosità, era proprio necessario scrivere in Inglese (su una repo Italiana)? 🤣🤣🤣

**Comment by ale8530** [comment]
Che rom monti?

**Comment by ale8530** [comment]
No reply
