### ISSUE TITLE
alcuni piccoli refusi

### ISSUE THREAD

**Issue by mymo1982** [MishFdM/MIUI_V10_Italy#63]
In Mido:

Nell'app fotocamera, "Capovolgi" dovrebbe essere "Tilt shift", mentre "Rafforza" dovrebbe essere "Raddrizza".

Inoltre, in "impostazioni/impostazioni aggiuntive/privacy/orgine sconosciuta"si dovrebbe correggere la parola "fanti" in "fonti".

Grazie :)

**Comment by 0rlaf** [comment]
https://github.com/MishFdM/MIUI_V10_Italy/pull/65
