### ISSUE TITLE
Contapassi

### ISSUE THREAD

**Issue by mario1944** [MishFdM/MIUI_V10_Italy#77]
Il contapassi non funziona con la lingua italiana

**Comment by ale8530** [comment]
Issue rifiutata per mancanza dettagli

**Comment by mario1944** [comment]
Il contapassi resta sempre sul zero, con lingua inglese invece funziona!

Il 21 agosto 2018 08:57:34 CEST, ale8530 <notifications@github.com> ha scritto:
>Issue rifiutata per mancanza dettagli
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MishFdM/MIUI_V10_Italy/issues/77#issuecomment-414569829

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by ale8530** [comment]
Devi fornire la rom di riferimento da cui provieni, questo bug report non va bene per queste cose

**Comment by mario1944** [comment]
Miui 10 Xiaomi.eu 8.8.9 per mi 4s

Il 21 agosto 2018 15:46:09 CEST, ale8530 <notifications@github.com> ha scritto:
>Devi fornire la rom di riferimento da cui provieni, questo bug report
>non va bene per queste cose
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MishFdM/MIUI_V10_Italy/issues/77#issuecomment-414679179

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by ale8530** [comment]
Sento lo sviluppatore

**Comment by ale8530** [comment]
https://github.com/MishFdM/MIUI_V10_Italy/commit/168be0f4b655238963b011e1844f25a49aa9217c
