### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by alessandranava** [MishFdM/MIUI_V10_Italy#97]
Usando Google Chrome e in base al sito su cui si naviga non compare in alto la barra con l'orario, il segnale di rete, la percentuale della batteria ecc .

**Comment by 0rlaf** [comment]
Questa è la sezione bug traduzioni, non generici di sistema.

**Comment by ale8530** [comment]
Confermo quanto indicato da orlaf

**Comment by 0rlaf** [comment]
> Quale è la sezione generici di sistema? Grazie

Il forum di miui.it
